// General Constants
var HUB_SERVER_URL = 'http://localhost:3851';


// Chrome Runtime Messages
var FETCH_YOUTUBE_CHANNEL_ID_MSG = 'FETCH_YOUTUBE_CHANNEL_ID';
var GET_CHANNEL_ID_MSG = 'GET_CHANNEL_ID';
var NOTIFY_CHANNEL_ID_FOUND_MSG = 'NOTIFY_CHANNEL_ID_FOUND';




// Local Storage Constants
var USER_YOUTUBE_ID = 'USER_YOUTUBE_ID';
var SUBSCRIPTIONS_LIST = 'SUBSCRIPTIONS_LIST';
var COLLECTIONS_LIST = 'COLLECTIONS_LIST';
var EXTENSION_STATE = 'EXTENSION_STATE';
var SELECTED_COLLECTION = 'SELECTED_COLLECTION';
var NEW_COLLECTION_TITLE = 'NEW_COLLECTION_TITLE';
var DISPLAY_MESSAGE = 'DISPLAY_MESSAGE';



// Extension States
var FETCHING_YOUTUBE_CHANNEL_ID = 'FETCHING_YOUTUBE_CHANNEL_ID';
var CHANNEL_ID_FOUND = 'CHANNEL_ID_FOUND';
var FETCHING_SUBSCRIPTIONS = 'FETCHING_SUBSCRIPTIONS';
var INITIALIZED = 'INITIALIZED';





















